[package]
name = "stac-server"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = "0.6"
stac = { version = "0.3", git = "https://github.com/gadomski/stac-rs", branch = "stac-api/server-updates" }
stac-api = { version = "0.1", git = "https://github.com/gadomski/stac-rs", branch = "stac-api/server-updates" }
stac-api-backend = { version = "0.0.1", path = "../stac-api-backend" }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
toml = "0.6"
tokio = { version = "1.23", features = ["fs", "io-util"] }
url = "2.3"

[dev-dependencies]
stac-api-backend = { version = "0.0.1", path = "../stac-api-backend", features = ["memory"] }
tokio = { version = "1.23", features = ["rt", "macros"]}
tokio-test = { version = "0.4" }
tower = "0.4"
