[package]
name = "stac-server-cli"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.6"
clap = { version = "4", features = ["derive"] }
stac = "0.3"
stac-async = "0.3"
stac-api = { version = "0.0.1", path = "../stac-api", features = ["pgstac"] }
stac-server = { version = "0.0.1", path = "../stac-server" }
tokio = { version = "1.23", features = ["macros", "rt-multi-thread"] }
tokio-postgres = "0.7"

[[bin]]
path = "src/main.rs"
name = "stac-server"
test = false
doc = false
doctest = false
