version: "3"
services:
  stac-server-rs:
    image: gadomski/stac-server-rs
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    command:
      - config.toml
    depends_on:
      - database
  database:
    image: ghcr.io/stac-utils/pgstac:v0.6.10
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=localhost
      - PGDATABASE=postgis
    ports:
      - "5432:5432"
    command: postgres -N 500
