[package]
name = "stac-api-backend"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait = "0.1"
serde = "1"
serde_json = "1"
stac = { version = "0.3", git = "https://github.com/gadomski/stac-rs", branch = "stac-api/server-updates", features = ["set_query"] }
stac-api = { version = "0.1", git = "https://github.com/gadomski/stac-rs", branch = "stac-api/server-updates" }
thiserror = "1"

[dev-dependencies]
stac = { version = "0.3", git = "https://github.com/gadomski/stac-rs", branch = "stac-api/server-updates", features = ["jsonschema", "set_query"] }
tokio = { version = "1.24", features = ["rt", "macros"] }

[features]
memory = []
