name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --verbose
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Set up Conda cache
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ hashFiles('scripts/environment.yml') }}
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: "3.11"
          environment-file: scripts/environment.yaml
          activate-environment: validate
      - name: Build
        run: cargo build
      - name: Validate
        run: scripts/validate
