name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Format
        run: cargo fmt --verbose
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
