name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  memory:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Set up Conda cache
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ hashFiles('scripts/environment.yaml') }}
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: "3.11"
          environment-file: scripts/environment.yaml
          activate-environment: validate
      - name: Validate
        run: scripts/validate
  pgstac:
    runs-on: ubuntu-latest
    services:
      pgstac:
        image: ghcr.io/stac-utils/pgstac:v0.8.1
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgis
          PGUSER: username
          PGPASSWORD: password
          PGDATABASE: postgis
        ports:
          - 5432:5432
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Set up Conda cache
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ hashFiles('scripts/environment.yaml') }}
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: "3.11"
          environment-file: scripts/environment.yaml
          activate-environment: validate
      - name: Validate
        run: scripts/validate --pgstac
