name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  memory:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install geos
        run: sudo apt-get update && sudo apt-get install libgeos-c1v5 && sudo rm -rf /var/lib/apt/lists/*
      - name: Install stac-api-validator
        run: pip install -r scripts/requirements.txt
      - name: Validate
        run: scripts/validate
  pgstac:
    runs-on: ubuntu-latest
    services:
      pgstac:
        image: ghcr.io/stac-utils/pgstac:v0.8.1
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgis
          PGUSER: username
          PGPASSWORD: password
          PGDATABASE: postgis
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install geos
        run: sudo apt-get update && sudo apt-get install libgeos-c1v5 && sudo rm -rf /var/lib/apt/lists/*
      - name: Install stac-api-validator
        run: pip install -r scripts/requirements.txt
      - name: Validate
        run: scripts/validate --pgstac
